baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Aceras Anthropophorum'
theme = ['hugo-theme-stack']
description = "Ο Aceras Anthropophorum εν ένα μικρόν φυτόν της οικογένειας των ορχιδέων. Βλαστά πας τες ξεροκαφκάλλες. Ζητά λλία πράματα για να ζήσει: ελευθερίαν, ησυχίαν τζαι ελάχιστες υλικές προϋποθέσεις. Στην Κύπρον εξιλείφτην λόγω της αλοάρκαστης ανάπτυξης. Αν κάποιος τον δει κάπου, να μεν το πει κανενού. Να μου πέψει μήνυμαν να πάμεν να θαυμάσουμεν τα φκιόρα του μαζίν τον Απρίλην. Υπόσχουμαι ότι δε θα τσαλαπατήσω ότι βλαστά γυρόν. Αναζητώ τζαι άλλου είδους ανθρωποφέρουσες ιδέες που τείνουν να ξιλειφτούν."
